--liquibase formatted sql
--changeset darkula:alter-table-menu-dinner-id-t

ALTER TABLE MENU_DINNER_ID_T ADD UNIQUE(DINNER_ID);
ALTER TABLE MENU_DINNER_ID_T ADD UNIQUE(MENU_ID);
ALTER TABLE MENU_DINNER_ID_T ADD FOREIGN KEY (MENU_ID) REFERENCES MENU_T(ID);