--liquibase formatted sql
--changeset darkula:alter-table-menu-item-t

ALTER TABLE MENU_ITEM_T ADD UNIQUE(MENU_ITEM_ID);
ALTER TABLE MENU_ITEM_T ADD UNIQUE(MENU_SECTION_ID);
ALTER TABLE MENU_ITEM_T ADD UNIQUE(MENU_ID);
ALTER TABLE MENU_ITEM_T ADD FOREIGN KEY (MENU_SECTION_ID) REFERENCES MENU_SECTION_T(MENU_SECTION_ID);
ALTER TABLE MENU_ITEM_T ADD FOREIGN KEY (MENU_ID) REFERENCES MENU_T(ID);