GET localhost:8080/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJidWJiZXIuZGlubmVyQGVtYWlsLmNvbSIsImdpdmVuX25hbWUiOiJidWJlciIsImZhbWlseV9uYW1lIjoiZGlubmVyIiwianRpIjoiYWRlNmUwZmUtNWJmYS00YjRjLWIyNjUtZTkxZmEwOWYzNzZlIiwiZXhwIjoxNjc4MDA4NDQwLCJpc3MiOiJJQnViZXJEaW5uZXIiLCJhdWQiOiJBQnViZXJEaW5uZXIifQ.Q9ICP8JxlXnCMTooILHn0zNuAFIqFTFROxlJ2amRl1o